### ISSUE TITLE
Fully rename the WordPress and WP thing

### ISSUE THREAD

**Issue by joglomedia** [notmattpress/notmattpress#8]
I really hate Matt actions, we should consider fully rename the WordPress, WP, wordpress, and wp, words from the code base. We want fully Mattless software, event only word related to Matt should be removed on this fork.

Greetz

**Comment by robertdevore** [comment]
Full renames are in the plans, but just haven't had the time to update the Action yet.

Feel free to submit PR's if you find text strings you think should be switched 🤘
